[package]
name = "rc_car_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sdl2 = { version = "0.37.0" }
byteorder = "1.5"

[build]
target = "x86_64-unknown-linux-musl"